
INSERT INTO questions (question, answers, correct_answer)
VALUES 
('What is the capital of Uruguay?', 'A: Montenegro, B: Montepelo, C: Montecarlo, D: Montevideo', 'D'),
('Which planet is known as the Red Planet?', 'A: Earth, B: Mars, C: Jupiter, D: Venus', 'B'),
('Who wrote "Hamlet"?', 'A: Dickens, B: Shakespeare, C: Chaucer, D: Austen', 'B'),
('What is the boiling point of water?', 'A: 90°C, B: 100°C, C: 110°C, D: 120°C', 'B'),
('What is the largest mammal?', 'A: Elephant, B: Gorilla, C: Blue Whale, D: Orca', 'B'),
('Which name does ''War Machine'' also go by?', 'A: Metal Warhorse, B: Steel Warrior, C: Iron Patriot, D: Captain Legend', 'C'),
('What is the flavour associated with the ''Oreo'' cookie?', 'A: Cookies and Cream, B: Rocky Road, C: Vanilla and Mousse, D: Mint', 'A'),
('In the story of Snow White, how many dwarfs are there?', 'A: 4, B: 5, C: 7, D: 6', 'C'),
('What is the main ingredient in the dish ''sushi''?', 'A: Fish, B: Seaweed, C: Wasabi, D: Rice', 'D'),
('How many sides does a hexagon have?','A: 4, B: 5, C: 6, D: 7','C'),
('What is the value of the integral of (1/(x^2 + 1)) dx from 0 to ∞?', 'A: π/2, B: π, C: 1, D: 0', 'A'),
('What is the characteristic polynomial of the matrix [1, 0; 0, 2]?', 'A: (x - 1)(x - 2), B: (x + 1)(x + 2), C: x^2 - 3x + 2, D: x^2 - 1', 'A'),
('Which video game features a character named "Link"?', 'A: Mario, B: Zelda, C: Metroid, D: Pokemon', 'B'),
('Which game series features the character "Master Chief"?', 'A: Halo, B: Call of Duty, C: Battlefield, D: Overwatch', 'A'),
('In "Minecraft", what material do you not need to create a pickaxe?', 'A: Iron, B: Emerald, C: Diamond, D: Gold', 'B'),
('What is the name of the robot playable character in ''Apex Legends?''', 'A: Pathfinder, B: Astro, C: Bastion, D: M.O.D.O.K', 'A'),
('Who is the enemy of ''Mr. Mxyzptlk''?', 'A: Batman, B: Spiderman, C: Ironman, D: Superman', 'D'),
('Who was the leader of the Soviet Union during the Cuban Missile Crisis?', 'A: Joseph Stalin, B: Nikita Khrushchev, C: Leonid Brezhnev, D: Mikhail Gorbachev', 'B'),
('What is the ''powerhouse of the cell?''', 'A: Nucleus, B: Ribosome, C: Mitochondrion, D: Endoplasmic Reticulum', 'C'),
('Which country was led by Fidel Castro from 1959 until his retirement?', 'A: Venezuela, B: Cuba, C: Brazil, D: Argentina', 'B'),
('What is the name of the world''s largest desert?', 'A: Sahara, B: Kalahari, C: Gobi, D: Antarctica', 'D'),
('What is the name of the first artificial Earth satellite launched by the Soviet Union in 1957?', 'A: Sputnik 1, B: Vostok 1, C: Luna 1, D: Kosmos 1', 'A'),
('What is the only country that is also a continent?', 'A: United States, B: Australia, C: South Africa, D: Ireland', 'B'),
('Which animal has the largest brain in relation to body size?', 'A: Sperm Whale, B: Dolphin, C: Elephant, D: Ant', 'D'),
('What is the specific term used to describe a type of sandstorm characterized by strong winds carrying a wall of dust and sand, reducing visibility and causing hazardous conditions?', 'A: Habeeb, B: Habaab, C: Haboob, D: Habuub', 'D'),
('Which one of these names belongs to a character in Dragon Ball Z?', 'A: Uub, B: Uud, C: Uul, D: Uuk', 'A'),
('What is the official animal of Scotland?', 'A: Dragon, B: Werewolf, C: Unicorn, D: Dinosaur', 'C'),
('What animal is known for its long neck and spots on its body?', 'A: Giraffe, B: Zebra, C: Cheetah, D: Leopard', 'A'),
('What is the shortcut for the “copy” function on most computers?', 'A: CTRL C, B: CTRL D, C: CTRL V, D: SHIFT C', 'B'),
('Night Crawler, member of the X-Men, has what kind of powers?', 'A: Teleportation, B: Invisibility, C: Laser Beams, D: Time Control', 'A'),
('Who wrote ''The Odyssey?''', 'A: Bart, B: Lisa, C: Homer, D: Ned', 'C'),
('In what year did the Chernobyl disaster occur?', 'A: 1951, B: 1976, C: 1991, D: 1986', 'D'),
('Who owns the stand ''Scary Monsters''?', 'A: David Bowie, B: Darius Brand, C: Diego Brando, D: Draymond Blackshear', 'C');
